name: comunicacion
description: Comunicacion Villada

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
    

  flutter_launcher_icons: "^0.7.3"

  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.16.0
  firebase_database: ^3.0.7
  
  loading_overlay: ^0.2.1
  bouncing_widget: ^1.2.0

  provider: ^4.3.2
  flutter_spinkit: "^4.1.2"
  
  english_words: ^3.1.5

  rxdart: ^0.24.1
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Comfortaa
      fonts:
          - asset: fonts/Comfortaa-Regular.ttf

  uses-material-design: true
  assets:
    - assets/its.jpg
    - assets/formulario.jpg