name: comunicacion
description: Comunicacion Villada

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"


dependencies:


  gradient_app_bar: ^0.1.3
  image_gallery_saver: '^1.5.0'
  image_picker_saver: ^0.3.0
  toast: ^0.1.5
  flutter:
    sdk: flutter

  http: ^0.12.2
  sqflite: any
  path_provider: any
    
  flutter_launcher_icons: "^0.8.0"

  firebase_auth: ^0.16.0
  firebase_database: ^3.0.7
  
  loading_overlay: ^0.2.1
  bouncing_widget: ^1.2.0

  provider: ^4.3.2
  flutter_spinkit: "^4.1.2"
  
  english_words: ^3.1.5

  rxdart: ^0.24.1
  flutter_bloc: ^6.0.1
  flutter_datetime_picker: ^1.2.5

  built_collection: ^4.3.2
  analyzer: ^0.39.0
  json_annotation: ^3.0.1

  pdf: ^1.11.2
  flutter_full_pdf_viewer: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  json_serializable: ^3.4.1


flutter:
  fonts:
    - family: Comfortaa
      fonts:
          - asset: fonts/Comfortaa-Regular.ttf
    - family: OpenSans
      fonts:
          - asset: fonts/OpenSans-Bold.ttf
  uses-material-design: true
  assets:
    - assets/its.jpg
    - assets/formulario.jpg